import type { Metadata } from "next";
import "@/styles/globals.css";

import { NuqsAdapter } from "nuqs/adapters/next/app";

import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";

import { blinka, inter, malibu } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen font-body antialiased",
					malibu.className,
					blinka.variable,
					inter.variable
				)}
			>
				<NuqsAdapter>
					<Header />
					{children}
					<Footer />
				</NuqsAdapter>
			</body>
		</html>
	);
}
