import type { Metadata } from "next";
import "@/styles/globals.css";

import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";

import { amandine, malibu } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"min-h-screen font-body antialiased",
					malibu.className,
					amandine.variable
				)}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
